TIMESLOT_DURATION = 3600 # seconds
TRAFFIC_LIGHT_STANDARD_DURATION = 120 #seconds
RED_LIGHT_STANDARD_DURATION = TRAFFIC_LIGHT_STANDARD_DURATION / 2
YELLOW_LIGHT_STANDARD_DURATION = 5 # seconds
GREEN_LIGHT_STANDARD_DURATION = RED_LIGHT_STANDARD_DURATION - YELLOW_LIGHT_STANDARD_DURATION

MIN_UNIT_OF_TIME = 5 # seconds
NUM_OF_VEHICLE_PER_TIME_UNIT_OUTPUT = 15

TRAFFIC_LIGHT_Y_ID = 0
FIRST_ROAD_IN_Y_ID = 1
SECOND_ROAD_IN_Y_ID = 3

TRAFFIC_LIGHT_X_ID = 1
FIRST_ROAD_IN_X_ID = 2
SECOND_ROAD_IN_X_ID = 4

FIRST_TIMESLOT_ID = 1
LAST_TIMESLOT_ID = 24

MOTORBIKE_COUNT_WEIGHT = 0.5
CAR_COUNT_WEIGHT = 1
TRUCK_COUNT_WEIGHT = 2.5